elements/altpowerbar.lua

Since 6.2, I guess, Blizzard changed ```UnitAlternatePowerInfo()``` by adding one more return value.
It is also illogical to override possibly existing ```OnLeave``` script.

altpowerbar: Some tweaks

---

elements/stagger.lua

Hi! Came across this issue. When we force stagger to update, no update actually happens beyond visibility check.

stagger: Perform an actual update on forced update event.

---

elements/runebar.lua

Since 6.2, `GetRuneCooldown` returns nil values during loading screens, which result in errors being spewed.
It is most likely an issue with the API, but it's probably best to check for it to avoid errors.
Discussion: http://www.wowinterface.com/forums/showthread.php?t=52535

runebar: Bail if GetRuneCooldown returns nil values

---

elements/castbar.lua

PetCastingBarFrame is only ever used for possessed units, we need to disable it on the player unit instead of the pet.
This resolves #220.

castbar: Kill the pet casting bar if we spawn a player castbar

---

elements/power.lua
elements/stagger.lua

This PR contains changes to the `colors` table of oUF found in the _powers_ element.

Legion power colors

---

elements/classicons.lua

This PR contains additions/deprecations for the classicons element for Legion.
It depends on #267 to work correctly for Legion.
It also eliminates the need for #223 and #240.

Legion classicons

---

elements/powerprediction.lua
oUF.xml

Here's my take on PCP.
I haven't added element description yet, cuz current implementation isn't set in stone, I'll add it when everything else is done.
It works quite similar to heal prediction element.
```lua
local mainBar = CreateFrame('StatusBar', nil, self.Power)
mainBar:SetReverseFill(true)
mainBar:SetPoint('TOP')
mainBar:SetPoint('BOTTOM')
mainBar:SetPoint('RIGHT', self.Power:GetStatusBarTexture(), 'RIGHT')
mainBar:SetWidth(200)
local altBar = CreateFrame('StatusBar', nil, self.DruidMana)
altBar:SetReverseFill(true)
altBar:SetPoint('TOP')
altBar:SetPoint('BOTTOM')
altBar:SetPoint('RIGHT', self.DruidMana:GetStatusBarTexture(), 'RIGHT')
altBar:SetWidth(200)
self.PowerCostPrediction = {
mainBar = mainBar,
altBar = altBar
}
```
As I said …

New power cost prediction element.

---

elements/runebar.lua

This PR contains changes to the runebar element for Legion.
It also eliminates the need for #112.

Legion runebar

---

elements/power.lua

Hi!
Title says it all. Here's an example.

power: Alternative power colours use both 0-1 and 0-255 ranges.

---

elements/totems.lua

Totem categories (fire, water..) have been removed. This fixes issue with ordering where the 1st totem casted is diplayed in the 2nd position, and the 2nd casted totem is displayed in the 1st position.

Legion totems

---

elements/power.lua

Another attempt on #286 
~~**Issues:**~~
~~I was not able to unset the atlas once it was set, despite following [blizzard's code](https://github.com/Gethe/wow-ui-source/blob/live/FrameXML/UnitFrame.lua#L486-L498). Also tried `power:SetStatusBarAtlas(nil)` which made `power:GetStatusBarAtlas()` return nil but it didn't change anything (btw `power:SetStatusBarAtlas()` errors, nil is required like in `:SetTexture`). So I must be missing something here, but don't know what.~~
~~To reproduce:~~
1. ~~set `Power.useAtlas` to true for the target frame in your layout~~
2. ~~create a demon hunter~~
3. ~~target yourself and then switch target to a normal mob (with a power resource not using an atlas)~~
**Limitations:**
All the coloring options in the power element could not be applied to atlases as …

power: allow using atlases

---

ouf.lua

Not providing events when calling UAE from 3rd-party sources
makes it very hard to debug should something go wrong.
Relevant issue: https://github.com/oUF-wow/oUF/issues/297#issuecomment-246696419.

core: Make sure UpdateAllElements has an event

---

oUF.xml

This should make every unitframe have low framestrata instead of medium (like the default unitframes), so it doesn't overlap certain windows like garrision stuff for example.

core: Change the framestrata to LOW

---

elements/runebar.lua

When CD ends, start time is set to 0, however it doesn't happen, when rune is energised, so we pass wrong info to layout, cuz we don't differentiate between these two events.
Proof:

runebar: Set cooldown start time to 0 if rune was energised

---

elements/castbar.lua

Also use `SetColorTexture` instead of `SetTexture` for setting the color.
This is the minimal approach so that nothing changes for current implementations layout wise,
However it is not optimal. The way to use it is to set `Castbar.holdTime` to `GetTime() + CONSTANT` in both `Castbar.PostCastFailed` and `Castbar.PostCastInterrupted` and show the castbar again. The user can also update the castbar text and max value if desired. Also, with the current behavior the bar will be hidden first (UNIT_SPELLCAST_STOP fires after the first UNIT_SPELLCAST_INTTERUPTED, which fires 4 times).
A more intuitive approach would be to handle this from the default element (including setting the castbar text to `_G.INTERRUPTED`/`_G.FAILED` to mimic the default UI) and leave the castbar hiding to the OnUpdate …

castbar: add a .holdTime option

---

elements/health.lua

In 7.1, UNIT_HEALTH and UNIT_MAXHEALTH sometimes fire with `nil` in place of a unit token. oUF should just skip any attempt at updating the Health element when this happens, so layouts don't need to add their own checks to avoid errors. The existing `if (self.unit ~= unit)` check isn't sufficient, because `self.unit` is naturally `nil` on header-spawned frames whose unit doesn't currently exist (eg. join a party with 4 players, have someone leave the group, the 4th party frame is hidden but still exists and has no `unit` key).

Ignore health updates with nil unit (Blizz bug in 7.1)

---

ouf.lua

Unless anyone knows a way of getting this without exposing it here, SecureStateDriver is pretty air-tight.

core: Expose header visibility

---

elements/stagger.lua

- Made it more fail-safe;
- Removed unnecessary var caching;
- Reordered PostUpdate arg list. Throughout oUF we always use `cur, max, ...` arg order.

stagger: Revamp Update function.

---

blizzard.lua
ouf.lua

Rebased commits from #312 onto dev branch. It'll be easier for us to work on it this way.
How-To:
- Register style via [`oUF:RegisterStyle`](https://github.com/oUF-wow/oUF/blob/3a57f683386f6365d3ef55aec1e2c4985233b5ff/ouf.lua#L317);
- Activate style via [`oUF:SetActiveStyle`](https://github.com/oUF-wow/oUF/blob/3a57f683386f6365d3ef55aec1e2c4985233b5ff/ouf.lua#L327);
- Call [`oUF:SpawnNamePlates`](https://github.com/oUF-wow/oUF/blob/3a57f683386f6365d3ef55aec1e2c4985233b5ff/ouf.lua#L569);
- *(In Gordon Ramsay's voice)* Done.
`oUF:SpawnNamePlates` has 3 optional args:
- `namePrefix`. If nil, style's name w/ `oUF_` prefix will be used instead. For example, if `namePrefix` is 'TestPrefix', your nameplates' will have names like 'TestPrefixNamePlate1', 'TestPrefixNamePlate2', etc...;
- …

Feature: oUF NamePlates

---

elements/power.lua

Consistency, only reasoning behind the previous order was to avoid compatibility breaking, but this is for 7.0.

power: Reorder PostUpdate args

---

elements/castbar.lua

`statusbar:SetReverseFill(true)` will make the bar fill from right to left, instead of the default left to right. This commit will adjust `SafeZone` to be on the appropriate side if this attribute is set.

castbar: Add support for reverse fill statusbars

---

elements/portrait.lua

`:SetUnit` is not available on Model

portrait: check for PlayerModel instead of Model

---

elements/range.lua

- removed unused ForceUpdate (unneeded because of how the element is updated)
- no need to check for `.Range` in OnUpdate - already done in Enable
- ~~show OnRangeFrame only once~~ rebased
- use `element.insideAlpha` instead of magic 1 in Disable

range: minor cleanup

---

elements/healthprediction.lua

Changes:
* ~~Renamed `absorbBar` and  `overAbsorb` sub-widgets to `damageAbsorbBar` and `overDamageAbsorb`. This will make their purpose more clear to newer users, will improve readability, and, lastly, their heal absorbing counterparts have "heal" in their names;~~
* Changed list of arguments that's passed to `PostUpdate` func. New arguments are `myIncomingHeal`, `otherIncomingHeal`, `damageAbsorb`, `healAbsorb`, `hasOverDamageAbsorb`, `hasOverHealAbsorb`. Basically, these are `cur` values of all status bars + 2 extras, for some reason we weren't passing the most important stuff, why?;
* Removed useless `overHealAmount` variable/arg, it's calculated for the sake of being passed to `PostUpdate`.

healthprediction: Element update

---

elements/classpower.lua

Currently, all bars are shown regardless of current power, and instead fills when the power is available.
This means with e.g. 0 combo points it shows 5 empty bars.
With this patch it shows only those who're (partially) filled.

classpower: Only show active bars

---

elements/runes.lua

start and duration are nil when the player is in a vehicle
boolean is a Lua type and should be in lowercase

runes: update docs

---

elements/classpower.lua

Added non-destro soul shards bugfix;
Removed `mod` arg, it's not really needed.
If someone for some reason needs a number of fragments, one can do `local frags = cur % 1` instead of `local frags = cur % mod`.

classpower: Element update

---

elements/castbar.lua

safeZonePercent is already multiplied by width below in SetWidth.
self.max is in seconds, and ms is in milliseconds - hence 1e5 is too big.
(safeZonePercent is actually a ratio, but that's not renamed here)

castbar: fix SafeZone width calculation

---

ouf.lua

Old method breaks with embedded instances of oUF.

core: Let the packager set a static version

---

ouf.lua

It's WIP fix for #402, unlike #403 it doesn't break raid vehicle frames in other raids like Ulduar or EoE.
Logic is quite straightforward. When you zone into Antorus, it'll hack raid frames, but when you zone out it'll unhack them. If you're in combat, this un/hackery will be delayed :grin::gun:
@pquerner, @Blazeflack, @Grimsbain test it, pls 😭 
Suggestions are also welcome...

core: Disable raid frames vehicle handling in Antorus raid

---

elements/healthprediction.lua

Fixes maths related to heal absorb and incoming heals values. Previously we're discarding the excess of heal absorbs, while it should've been used to adjust inc heals values.
~I'll also update element's docs tomorrow, an example of `PostUpdate` is required to show people how to properly imitate Blizz prediction bars' behaviour. In our case `absorbBar` needs to be dynamically appended to either health bar or `otherBar`, depending on which one is the rightmost.~
The main difference is that inc heals and heal absorbs are mutually exclusive now. If the amount of heal absorb is larger than the amount of inc heals, its value will be adjusted and inc heals will be discarded. and vice versa.
This issue was highlighted in #409.

[healthprediction] Update maths [WIP]

---

elements/auras.lua

This adds duration, expiration, dispelType and isStealable to the list of PostUpdateIcon arguments.
`duration` and `expiration` are needed by layouts for custom aura timers. This would spare them the need to call UnitAura again or use CustomFilter to access those values.
`dispelType` and `isStealable` are interesting because the auras element hides the aura border (.overlay) when the .showType/.showBuffType/.showDebuffType are not found, which is a strange behavior in the first place. So this is a way to allow layouts to react to it without breaking backwards compatibility.

Auras: PostUpdateIcon update

---

utils/changelog

`git shortlog` show commits in reverse order, so reverse them again

changelog: show newest commits on top

---

elements/auras.lua
elements/classpower.lua
elements/grouproleindicator.lua
elements/health.lua
elements/power.lua
elements/runes.lua
elements/threatindicator.lua
ouf.lua

The (very helpful!) links to wowprogramming.com in the inline documentation are currently throwing 404s. This can lead to quite some confusion (and did for me...). The fix was to just append ".html".

Update wowprogramming.com links in documentation

---

elements/auras.lua

This PR turns this:
Into this:

auras: prevent cooldown spiral from darkening count

---

ouf.lua

This PR removes a 10yo hack that's no longer needed.
However, if you do need to update an element before disabling it, use its `ForceUpdate` method:
```lua
unitframe['element']:ForceUpdate()
unitframe:DisableElement('element')
```
It's similar to what you're expected to do when you need to update an element after enabling it:
```lua
unitframe:EnableElement('element')
unitframe['element']:ForceUpdate()
```

core: Remove UpdateAllElements call from DisableElement

---

elements/health.lua
elements/power.lua

This will allow layout devs to toggle frequent updates w/o disabling and then re-enabling health and power elements.

Add SetFrequentUpdates method to health and power elements

---

elements/assistantindicator.lua
elements/grouproleindicator.lua
elements/leaderindicator.lua
elements/phaseindicator.lua
elements/portrait.lua
elements/pvpindicator.lua
elements/raidroleindicator.lua
elements/readycheckindicator.lua
elements/resurrectindicator.lua
elements/runes.lua
elements/summonindicator.lua
events.lua
ouf.lua
private.lua
units.lua

Basically, deciding silently for the layout which event is unitless is bad.
Events like PARTY_MEMBER_ENABLE, INCOMING_RESURRECT_CHANGED, PLAYER_SPECIALIZATION_CHANGED and others are all unit events but were always wrongly considered unitless.
The following code from a layout:
```lua
self:RegisterEvent('PLAYER_TOTEM_UPDATE', Update)
```
will produce the following error:
```
3x oUF\events.lua:98: Attempt to register unknown event "PLAYER_TOTEM_UPDATE"
[C]: ?
oUF\events.lua:98: in function `RegisterEvent'
oUF_Layout\elements\custom\totems.lua:75: in function `enable'
oUF\ouf-@project-version@.lua:113: in function `EnableElement'
oUF\ouf-@project-version@.lua:329: in function <oUF\ouf.lua:251>
(tail call): ?
oUF\ouf-@project-version@.lua:685: in function `Spawn'
oUF_Layout\layout.lua:7: in …
```

Patch unit events

---

events.lua
private.lua

Fixes the case were for an event with N handlers, N - 1 become unregistered during the execution loop. Before the patch in this case the handler table was converted to a function causing the for loop in the __call meta method to exit without calling it.

core: keep the event table even with one handler left

---

events.lua
ouf.lua

The main purpose of this PR was to address an issue where oUF wasn't updating pet frame's unit while switching between `pet`, `player`, and `vehicle` units while having a real pet summoned. In this sense it addresses the same issue as #481 does, but in a different way.
It also addresses few other issues related to headers, e.g., unintentional registration of unit events as unitless, excessive `UpdateAllElements` calls on GRU, etc.

core: Update the event system

---

elements/threatindicator.lua

Blizz updated the texture map we're using for the default texture, so it's a good opportunity to start using proper dedicated textures.
New:
Old (Current):

threatindicator: Use a better default texture

---

colors.lua
elements/health.lua
elements/power.lua
private.lua

This PR is the continuation of #467.
In stead of using `UnitSelectionColor` and guessing what's what, this iteration utilises a slightly modified version `UnitSelectionType` that's added in 8.1.5,
`.colorSelection` is pretty much a smarter version of `.colorReaction`.

[8.1.5] Add .colorSelection option to health and power elements

---

ouf.lua

This PR practically halves the amount of time spent on the nameplates' elements' updates.

core: Greatly reduced the number of UAE calls for the nameplates

---

elements/alternativepower.lua
elements/castbar.lua
elements/stagger.lua

Toggling visibility on enable may break layouts which have elements depending on the visibility of other elements.
```lua
local function OnHide(altpower)
local experience = altpower.__owner.Experience
if (experience) then
experience.Show = nil
experience:ForceUpdate()
end
end
```
`element:Hide()` in `elements/alternativepower.lua` would break the above if oUF_Experience has not yet been enabled (ForceUpdate is not avail). Waiting for PEW/ForceUpdate to toggle visibility is better, because relevant elements should have loaded until then.
This only presented itself with patch 8.1.5, maybe because of graphic changes made behind scenes.
A more resilient approach for the layout would be to check for the presence of ForceUpdate and not as above, so in this case it might be argued upon where the …

elements: do not toggle visibility on enable where it is part of the update process

---

elements/health.lua
elements/power.lua
elements/readycheckindicator.lua
elements/tags.lua
elements/threatindicator.lua
ouf.lua
private.lua

It's a cosmetic PR for the most part, however, it's needed to make the difference between Blizz's methods and our wrappers more obvious. While wrappers might share their names w/ og methods, inputs might be completely different.

Updated Private methods to use camelCase

---

events.lua

Fixes #497
This is a regression introduced after #399 by #472

core: handle pass-through events for eventless frames as unitless

---

elements/stagger.lua

VisibilityPath depends on the element being hidden.
Fixes https://github.com/oUF-wow/oUF/issues/495#issuecomment-485219143

stagger: fix visibility toggling

---

elements/tags.lua

This PR primarily is targetted at layout devs who have in-game configs. Its goal is to improve the process of creating custom tags via GUIs.
Normally, when you write a new tag in Lua, you can just store additional constants, tables, or helper methods in the higher level of scope, and then directly access those from your tag code. However, you can't really do that when your tag is just a string that's loaded via `loadstring`. Previously, you'd have to either create additional tables or even funcs inside the tag string, and those would be created on every single tag func call, or create global vars, which isn't optimal at all.
So, let's say you want to create a tag named `"tag"` that returns `"yes!"` if your target's class is either mage or shaman, then your tag's code will look like this: …

tags: Update the system

---

blizzard.lua

Due to [UI changes in 8.2](https://us.forums.blizzard.com/en/wow/t/ui-changes-in-rise-of-azshara/202487), nameplates can only be parented to their base plates.
```
We added new restricted frames system that affects frame anchoring:
- Frames that are anchored to a restricted frame can only have their other anchors
set to frames within that same anchor hierarchy
- New restricted frames include  
- Nameplates
```
W/o it you'll encounter errors like this one:
```
Message: Interface\FrameXML\CompactUnitFrame.lua:1901: Action[SetPoint] failed because
[SetPoint would result in anchor family connection]: attempted from:
NamePlate1UnitFrame:SetAllPoints.
```

blizzard: Do not re-parent nameplates

---

elements/auras.lua

Due to [8.2 UI changes](https://us.forums.blizzard.com/en/wow/t/ui-changes-in-rise-of-azshara/202487), we should avoid parenting GameTooltip to frames with anchoring restrictions, otherwise, GameTooltip will inherit said restrictions.
This PR addresses #510, but it also adds an option to adjust GameTooltip's anchor point w/o the need to using the `CreateIcon` override.

auras: Add .tooltipAnchor option

---

elements/tags.lua

In its current form it fails to get `tagEnd` correctly.
Current:
```
[tag] => tag 2 -2
[>tag] => tag 3 -2
[>>tag] => tag 4 -2
[tag<] => tag 2 4
[tag<<] => tag< 2 5
[>tag<] => tag 3 5
[>>tag<<] => tag< 4 7
```
New:
```
[tag] => tag 2 -2
[>tag] => tag 3 -2
[>>tag] => tag 4 -2
[tag<] => tag 2 4
[tag<<] => tag 2 4
[>tag<] => tag 3 5
[>>tag<<] => tag 4 6
```

tags: Fix getTagName method

---

elements/castbar.lua

In Legion and BfA some world interaction doen't have icon for casting spell.
You can test it with https://www.wowhead.com/spell=182547/grappling-gun in Stormheim.

castbar: Add fallback icon

---

elements/phaseindicator.lua

This adds tooltip support for the phase indicator for Shadowlands. It is backwards compatible.

PhaseIndicator: Add Tooltip Support

---

elements/runes.lua

Death Knights start at level 8 without a spec and GetSpecialization() returns 5. Backwards compatible.

runes: fix for death knights without specialization in Shadowlands

---

elements/tags.lua

This PR will update oUF tags syntax.
Currently, a complete oUF tag looks like this `[prefix>tag-name<suffix]`, however, using `>` and `<` as delimiters isn't really convenient due to them being fairly popular characters for tags. So this PR will change `>` to `$>` and `<` to `$<`.
This PR also adds a way for users to pass additional arguments to tag functions via `()`, for example `[tag-name(a,r,g,s)]`, a normal comma `,` is used as a delimiter, these will be passed to your tag function. So in case of `[tag-name(a,r,g,s)]`, `tag-name` function well receive 6 arguments: `unit`, `realUnit`, `'a'`, `'r'`, `'g'`, and `'s'`. 
With these changes a complete oUF tag will look like this `[prefix$>tag-name$<suffix(a,r,g,s)]`, only `tag-name` is required, `prefix$>`, `$<suffix`, and `(a,r,g,s)` are …

tags: Update tag syntax

---

elements/castbar.lua

The purpose of this PR is to revamp the castbar element.
It's been largely untouched for almost a decade, there's a number of features missing, and the amount of code duplication is mind-boggling.
The first goal is to get rid of excessive code duplication by merging events' handlers like so:
- `UNIT_SPELLCAST_START` + `UNIT_SPELLCAST_CHANNEL_START` => `CastStart`
- `UNIT_SPELLCAST_DELAYED` + `UNIT_SPELLCAST_CHANNEL_UPDATE` => `CastUpdate`
- `UNIT_SPELLCAST_STOP` + `UNIT_SPELLCAST_CHANNEL_STOP` => `CastStop`
- `UNIT_SPELLCAST_INTERRUPTED` + `UNIT_SPELLCAST_FAILED` => `CastFail`
- `UNIT_SPELLCAST_NOT_INTERRUPTIBLE` + `UNIT_SPELLCAST_INTERRUPTIBLE` => `CastInterruptible`
Changes:
Because a good half of events' handlers was removed, some of callbacks were removed as well, others were renamed …

castbar: Element revamp

---

elements/alternativepower.lua

This is not backwards compatible because layouts might have relied on `.barType`, `.powerName` and `.powerTooltip` which were previously exposed on the element. `.__barID` and `.__barInfo` are now exposed on the element as a replacement.

alternativepower: replace deprecated UnitAlternatePowerInfo

---

colors.lua
elements/additionalpower.lua
elements/alternativepower.lua
elements/classpower.lua
elements/health.lua
elements/power.lua
elements/powerprediction.lua
elements/runes.lua
elements/stagger.lua
elements/threatindicator.lua

The main goal of this PR is to separate colour updates from value updates where possible. So instead of being bundled up as one big `Update` function that handles both maths/behaviour and colouring, there will be two functions:
- `Update` for maths and behaviour
- `UpdateColor` for colouring
This way users will be able to override these individually. Why would we want that? Because, at least from my experience, layout devs tend to override our `Update` functions to alter or completely disable the colouring.
In addition to that, new colours and colour-related options will be added to oUF and its elements. For instance, threat and alternative power colours weren't present in the `oUF.colors` table.

Update the colouring of elements

---

elements/stagger.lua

Visibility relies on it.
Fixes #553

stagger: hide the element in Enable

---

elements/alternativepower.lua

ElvUI report:
> While doing the quest "Call of the Raven Mother" in Dreanor, I got these errors. I'm running the latest Dev version of ElvUI
```
Message: ...ns\ElvUI\Libraries\oUF\elements\alternativepower.lua:215: Usage: UnitIsUnit("unit", "otherUnit") Time: Sat Oct 17 15:06:29 2020 Count: 4 Stack: ...ns\ElvUI\Libraries\oUF\elements\alternativepower.lua:215: Usage: UnitIsUnit("unit", "otherUnit") [string "=[C]"]: in function UnitIsUnit'
```

alternativepower: remove the realUnit check from the visibility condition

---

elements/powerprediction.lua

First of all, this PR adds support for mutating spells like monk's Vivify (116670) whose spell power and cost change depending on the player's current spec. The `GetSpellPowerCost`'s output contains multiple tables, if a spell can change its properties in such a way:
```lua
Dump: value=GetSpellPowerCost(116670) 
[1]={ 
[1]={ 
hasRequiredAura=false, 
type=0, 
name="MANA", 
cost=0, 
minCost=0, 
requiredAuraID=137024, 
costPercent=4, 
costPerSec=0 
}, 
[2]={ 
hasRequiredAura=false, 
type=3, 
name="ENERGY", 
cost=0, 
minCost=0, 
requiredAuraID=137023, 
costPercent=0, 
costPerSec=0 
}, 
[3]={ 
hasRequiredAura=true, 
type=3, 
name="ENERGY", 
cost=30, 
minCost=30, 
requiredAuraID=137025, 
costPercent=0, 
costPerSec=0 
} 
}
```
So we should account for that.
Secondly, rn there's a bug where the …

Update power prediction

---

elements/phaseindicator.lua

Turns out `UnitPhaseReason` is buggy after all 😁🔫

phaseindicator: Check phase only for player units

---

elements/tags.lua
events.lua
private.lua

In early-mid BfA `RegisterEvent`, `RegisterUnitEvent`, and `UnregisterEvent` started throwing errors, it wasn't a problem until recently, in SL Blizz started renaming and removing events which in turn started breaking oUF which wouldn't happen prior to the aforementioned error change, it'd just fail silently and wouldn't affect the framework. Wrapping these functions, where it's needed, with `xpcall`s will give layout devs, plugin devs, and us extra time to gather, report, and/or react to this kind of issues without breaking oUF itself since it will load and continue to function properly despite all the event errors.
This **WILL NOT** stop error messages from popping up.

Event wrapper

---

elements/tags.lua

When calling `table.remove` on an indexed table the whole table is shifted to fill the gap, thus `next` will skip one fontstring and call it a day. This has the potential of leaving the fontstring in the events table and still being processed when updating tags, resulting in an error from the eventhandler trying to call `UpdateTag` on it.

tags: Untag fontstrings correctly

---

events.lua
private.lua

As it's brought to my attention by @myzb, #563 kinda broke headers due to the fact that at the very beginning headers might not have legit units, so they don't pass the unit check, so the code doesn't even reach the event registration part. This PR addresses the issue by replacing all the wrappers with one `validateEvent` call.

Event wrapper fix

---

elements/auras.lua

This PR addresses: #570. This happens when users update options on the fly which my previous workaround didn't take into consideration, prob because I don't use that option myself 🥺
I also added tests for forbidden `GameTooltip`s, it's not super common, but it happens, I personally encountered it few times.

auras: Update workaround for frames with anchoring restrictions

---

ouf.lua

Elements might take care of updates themselves, so they should be not forced to pass `update` to `oUF:AddElement`.
This is currently the case with the Range element.
This partially reverts what was done in response to #579.

core: make element's update optional

---

.github/workflows/release.yml

We need to update the packager version to push the next version due to changes in hosting sites.
Also, workflows no longer support short sha, but the packager is now being tagged.

Update packager version

---

elements/tags.lua
private.lua

Why?
Honestly, the way we handle invalid tags is kinda archaic. I don't know any modern apps that support tags, for instance, audio players like aimp or foobar, that completely break down if a user dares to use an invalid tag or make a typo. Invalid tags either are rendered as plain text or aren't rendered at all. I chose the former approach because this way it's more obvious what's actually broken.
Moreover, it's not 2004 anymore, nowadays many layouts have in-game configs that allow users to create custom tag strings, so if a dev removes a tag with an update, users who used said removed tag in their custom tag strings simply won't be able to load the ui until they either edit saved vars manually or wipe them entirely. Which isn't desirable to say the least.
oUF will continue to throw …

tags: Render invalid text as plain text

---

elements/tags.lua

It's most likely a leftover from per-TW times, but `UnitLevel` itself is no longer used for displaying info about units.

tags: Use UnitEffectiveLevel instead of UnitLevel

---

elements/threatindicator.lua

I'm not exactly sure if I should use old `wow.gamepedia.com` or new `wowpedia.fandom.com` links here. I wonder if we should review docs everywhere 😒

threatindicator: Fix docs

---

events.lua
private.lua

Throw a custom error whenever something attempts to register a
unitless event without the unitless flag.

core: Check if event is unitless

---

ouf.lua

Sometimes frames get stuck with outdated unit info because of loading screens, needless to say it ends up breaking things.
Thanks to @linaori for reporting it and then testing the fix.

core: Evaluate units on PEW

---

elements/tags.lua

This fixes `'[ ($>test:tag<$)]'` resulting in ` (42` instead of ` (42)` in a backwards compatible way.
Here a simple use case for testing in case I missed something:
```lua
local function getBracketData(tag)
-- full tag syntax: '[prefix$>tag-name<$suffix(a,r,g,s)]'
local prefixEnd, prefixOffset = tag:match('()$>'), 1
if(not prefixEnd) then
prefixEnd = 1
else
prefixEnd = prefixEnd - 1
prefixOffset = 3
end
local suffixEnd = (tag:match('()%(', prefixOffset + 1) or -1) - 1
local suffixStart, suffixOffset = tag:match('<$()', prefixEnd), 1
if(not suffixStart) then
suffixStart = suffixEnd + 1
else
suffixOffset = 3
end
return tag:sub(prefixEnd + prefixOffset, suffixStart - suffixOffset),
prefixEnd,
suffixStart,
suffixEnd,
tag:match('%((.-)%)', suffixOffset + 1)
end
local function getAffixes(tag, …
```

tags: look for args in the suffix only

---

elements/additionalpower.lua
elements/alternativepower.lua
elements/auras.lua
elements/classpower.lua
elements/health.lua
elements/power.lua
elements/runes.lua
elements/stagger.lua
elements/threatindicator.lua
units.lua

Layouts using metatables to override default colors might not have named components.
This is partial revert of da7554aa.

elements: reference color components by index instead of name

---

ouf.lua
units.lua

Had to rework the way we handle eventless or "invalid" units because unlike `"boss1..5"` new `"boss6..8"` units can't be used for `RUE`, it silently fails and falls back to `RE`. The backend seems to be f*cking raw™. Along the way cleaned the code up a bit and fixed a couple of bugs I stumbled upon 😋 
So now instead of using internal `Private.enableTargetUpdate(object)` there's `oUF:HandleEventlessUnit(object)` that can be overridden by users in case they need to do something else in there.
Also, instead of creating a new `OnUpdate` for each frame we now handle eventless unit frames the same way we handle eventless tags, so there's one `OnUpdate` per timer.

core: Rework how eventless units are handled

---

ouf.lua

Vehicle events fire when the player not only enters/exits a vehicle, but also when the player changes sits. In this case both units on the unit frame will stay the same, so `UAE` won't be called which in turn leaves the frame with outdated info.
We need to run `UAE` so the frame updates properly.

core: Run UAE on UEV

---

.luacheckrc
blizzard.lua

Blizz reworked how their party frames work, they now use pools. Boss frames still work the old way, btw, no need to change anything there.

blizzard: Properly disable party frames

---

.luacheckrc
blizzard.lua

Currently it doesn't disable arena prep frames, this PR addressed that.
I was thinking about reformatting the boss block as well, but its container doesn't do anything smart, so I left it as is. I still removed that `string.format` call. Why was it there?

blizzard: Properly disable arena frames

---

blizzard.lua

I did Oculus and Malygos with this and didn't get any taints or see any issues whatsoever.
The source from the extra PlayerFrame events are from 2010 (Wrath):
- https://github.com/oUF-wow/oUF/commit/4d66082e6be7727ccc4b9489de1164809a515dea
- https://github.com/oUF-wow/oUF/commit/03eb8217d5c4a4a7ca8384b623da24afb78ad533
Fixes #622

Remove problematic legacy code

---

blizzard.lua
ouf.lua

This one reduces our footprint. Because we hooked the `OnEvent` handler oUF got EVERYTHING that's happening in and because of that function attributed to it. So in addons like ACU we'd get hugely inflated numbers without actually doing anything at all 😒🔫
Before:
After:
"Free performance" 🤣 Just to be clear, there's no actual performance improvement in this PR. It's just a quirk of how function hooking works.

core: Update nameplate hook

---

elements/tags.lua

The element desperately needed some love.
The main goal of this PR was to increase the performance of the element. Tags were originally written with standard unit frames in mind, and they're fairly static. But with the introduction of the nameplates some performance issues reared their ugly heads. Unfortunately, it took me a while to get to this because everything was... still working 😅
There's generally two areas of improvement:
- **Staggered updates.** Each tag string usually has multiple events registered for its updates, and quite often they fire in rapid succession while the data that's being displayed stays the same. So instead of updating a tag string each time any of its events fires, we just mark it for an update when that happens, but we'll update it only once every 0.25s or 4 …

tags: Update element

---

elements/tags.lua

After experimenting for a bit, I decided to adjust these values to allow for greater smoothness.
There's very little difference below 0.06s, but it's such an odd value that I picked 0.05s as the new minimum.

tags: Adjust eventTimerThreshold

---

blizzard.lua
ouf.lua

That `.isHooked` thingy was kinda gaudy, we don't do that anymore.
Also finally added widget and soft target containers to our nameplates. Better late than never.

NamePlate fixes

---

elements/additionalpower.lua

Additional power was rewritten on Blizz end. The changes are quite substantial, but we can't break things on our end rn, so I limited the scope of the update.
But I'll have to rewrite the element for 11.x.

additionalpower: Update vars

---

elements/readycheckindicator.lua

Blizz moved to atlases, but for the sake of compatibility we'll keep using old textures until the next major.

readycheckindicator: Hardcode icon textures

---

elements/castbar.lua

Empowered casts needed some love.
First of all, I added missing `PostUpdatePips` callback, users basically had no other option, but to override `CreatePips` and then jump through the hoops in `PostCastStart`.
Secondly, I added `PostUpdateStage` to notify the layout whenever the current stage changes.

castbar: Improve empowered cast handling

---

.luacheckrc
ouf.lua

They can be disabled in other ways than setting `frame.IsPingable = false`, but it's the simplest way (other methods involve attributes).

core: Support contextual pings

---

ouf.lua

When header children spawn during combat (e.g. a raid member joins) it would throw an error because we can't set attributes then.
Moving the attribute setter into a non-header block plus `initialConfigFunction` solves this, while we gotta keep the Mixin call where it was as the Mixin function nor the arg we pass through it exists in a secure environment.
Ref https://github.com/oUF-wow/oUF/pull/659#discussion_r1375492483

core: Fix contextual ping on header children

---

elements/healthprediction.lua

In 10.2 Blizz broke status bars a bit. Previously, when the bar was empty it was just that, empty, its texture width would be 0. But now it does the opposite of that, while the texture is not visible, it's actually set to the full width. And on top of that it breaks all the anchors.
So instead of this:
We now get this:

healthprediction: Fix unwanted statusbar behaviour

---

elements/healthprediction.lua

healthprediction: Remove unnecessary hack

---

colors.lua

In 10.2.5 the `predictionColor` subtable was added to most colours which broke our stagger detection. So instead of checking for subtables, it's easier to check if r/g/b entries are present.
Alternatively, it might be even better to check if a colour is `"STAGGER"` specifically, it's not like we'll be able to automagically catch a new colour if it has subtables as well because it might have differently named subtables.

colors: Update color fetching

---

elements/classpower.lua

UPF is a very spammy event, and using it for something like class powers feels like an overkill. They simply don't continuously regen like , let's say, rogue's Energy. The only reason why we use UPF is because it's been this way for over a decade at this point 😒
I'm not sure if there's any drawbacks to using UPU hence the name of the PR. I'll switch my own UI to UPU to gather as much feedback as possible from its users, but help from others is always welcome 😊

Investigate switching to UPU from UPF for class powers

---

elements/tags.lua

`GetThreatStatusColor` no longer accepts `nil`. Before 10.2.6 it used to return the same colour data for `nil` and `0`, see [wiki](https://warcraft.wiki.gg/wiki/API_GetThreatStatusColor). It also no longer accepts `-1`, but we don't use that.
Fixes #673.

tags: Fix threatcolor tag

---

.luacheckrc
blizzard.lua
colors.lua
elements/additionalpower.lua
elements/alternativepower.lua
elements/auras.lua
elements/classpower.lua
elements/grouproleindicator.lua
elements/health.lua
elements/healthprediction.lua
elements/power.lua
elements/powerprediction.lua
elements/pvpclassificationindicator.lua
elements/range.lua
elements/runes.lua
elements/stagger.lua
elements/summonindicator.lua
elements/threatindicator.lua
ouf.lua
units.lua

In TWW Blizz added this new thingy, the temporary max health loss bar. 
In this pic the max health was reduced by 50%, but the player is still at 100% health, it's just the total available amount of hp that's reduced temporarily, my assumption so far is that it's due to some raid/dungeon mechanics/auras hence the "temporary" bit in its name. This bar is kinda similar to "Reserved Life" from Path of Exile.

[WIP] TWW Support

---

elements/totems.lua

In https://github.com/oUF-wow/oUF/commit/c08b0d7a954b20ea55883ebafdefe7ecc6c1ea8d the constant was replaced with `5`, even though it has always represented `4`.
Mentioned in #701.

totems: Use 4 elements in the example

---

ouf.lua

It's a common practice to hide nameplates by adjusting their alpha, but this has adverse effects on blizzard-managed widgets, affecting gameplay in an (usually) accidental way.

core: Nameplate sub-widgets should ignore alpha

---

colors.lua

oUF expects a preceding addon to implement this (and hit the OnLoad clause), or a succeeding addon (and hit the ADDON_LOADED clause). If the addon embedding oUF implements CUSTOM_CLASS_COLORS this will never run since oUF is typically loaded as a library early (voiding the OnLoad clause), and then some unrelated addon is responsible for triggering ADDON_LOADED, which can fail in scenarios where the embedder is the only/last addon to load.
By adding PEW as a last-resort event we make sure this doesn't happen, but we lose the ability for addons implementing CUSTOM_CLASS_COLORS as load-on-demand (which I don't think exists anyways, and would be dumb considering how addons are expected to consume the callbacks).
Reported by Simpy from the ElvUI team.

colors: Load class colors on PEW

---

ouf.lua

10 boss frames seem to be a thing for a while. And I double checked if it's still necessary to do this, unit events are still not supported for `"boss6"` and beyond.

core: Handle up to 10 boss frames

---

.luacheckrc
elements/classpower.lua
elements/runes.lua
elements/stagger.lua
elements/tags.lua

Updated all deprecated APIs I could find, and no, `GetSpecializationInfoByID` wasn't namespaced unlike the rest.

API updates for 11.2
