oUF-wow/oUF

- elements/classicons.lua
Identical to stagger update issue #254
> classicons: Actually update widgets on forced update.

- elements/health.lua
- elements/power.lua
This PR contains fixes for the health and power elements for Legion and its updated tapping API.
> Legion tapping

- elements/readycheck.lua
This PR updates the ReadyCheck element to use the Animation widget system to handle fading.
It also fixes some issues it had with updating properly if the group changed or during disconnects.
An added bonus is more options and hooks, plus it improves the readability, making it easier to manage in the future.
Please test, I haven't looked at performance nor Legion for this one.
> ReadyCheck updates

- elements/tags.lua
This PR contains additions/deprecations for the tags element for Legion.
> Legion tags

- elements/druidmana.lua
This PR contains changes for the druidmana element for Legion, as more classes supports it.
These commits are compatible with both live and beta clients
> Legion druidmana

- elements/cpoints.lua
- elements/tags.lua
This PR contains changes to the cpoints element.
These commits are compatible with both live and beta clients, this is not a PR specific to Legion, just something I found while iterating over all the elements while creating the Legion updates.
> Legion combopoints

- elements/classicons.lua
> classicons: Add fallback texture color for vehicles

- elements/classicons.lua
> classicons: Update when max power changes

- elements/classicons.lua
- elements/health.lua
- elements/power.lua
This cleans up all the pre-legion compatibility checks that were merged.
I've also rebased my other commits (#265, #269) to not include this.
> Post-Legion cleanup

- elements/aura.lua
>  aura: Fixed issue which was causing /fstack error.

- elements/classicons.lua
> classicons: Make sure we update for talent changes for druids

- elements/additionalpower.lua
- oUF.xml
> druidmana: Rename element to "AdditionalPower"

- elements/totems.lua
It will be hidden with oUF:DisableBlizzard()
Mentioned here: https://github.com/oUF-wow/oUF/pull/283#issuecomment-239676805
> totems: TotemFrame is parented to PlayerFrame

- ouf.lua
Fixes https://github.com/oUF-wow/oUF/issues/257
Closes https://github.com/oUF-wow/oUF/pull/258
It would be nice if someone manages to test this is a raid/party
> core:  update the pet frame properly after entering/exiting a vehicle

- elements/tags.lua
Addresses request https://github.com/oUF-wow/oUF/issues/247.
> tags: Added 'powercolor' tag.

- elements/classicons.lua
- ouf.lua
> classicons: Fake the unit if the player is in a vehicle

- elements/aura.lua
It's getting a bit silly really :confused:.
> aura: Update returns from UnitAura

- elements/alternativepower.lua
Made an oopsie with ca31015791c7ad8832d121be32ee71958162042e. This fixes it
> alternativepower: fix Update when called from Visibility on hide

- elements/pvpindicator.lua
> pvpindicator: Swap factionGroup only for player

- elements/alternativepower.lua
> alternativepower: Add unit to PostUpdate args

- elements/threatindicator.lua
> threatindicator: Register necessary events for nameplates support

- elements/classpower.lua
The issue was brought up by @Gethe in https://github.com/oUF-wow/oUF/issues/346.
We ended up overhauling entire element 😀🔫
> classpower: Element revamp.

- elements/range.lua
> range element fix

- colors.lua
- elements/additionalpower.lua
- elements/alternativepower.lua
- elements/auras.lua
- elements/castbar.lua
- elements/classpower.lua
- elements/health.lua
- elements/healthprediction.lua
- elements/portrait.lua
- elements/power.lua
- elements/powerprediction.lua
- elements/range.lua
- elements/runes.lua
- elements/stagger.lua
- elements/tags.lua
- elements/totems.lua
- events.lua
- factory.lua
- ouf.lua
Mostly rewording and bringing in-line with the current [guidelines](https://github.com/oUF-wow/oUF/wiki/Guidelines-for-Layout-oriented-Documentation).
Need (?) function type headers for funcs in ouf.lua, everywhere else in core I used the name of the containing file (tell me if this is ok).
> Docs review

- colors.lua
- elements/runes.lua
This patch reflects 7.2.5 changes to DK's rune bar.
> runes: Add colouring support

- elements/tags.lua
- Explain what .frequentUpdates does for tags with events
- Don't suggest using .overrideUnit in sample code
- Minor comment changes in sample code
> tags: Update documentation

- elements/runes.lua
JIC, I had a bad dream about this line of code today... Bad omen 💀
> runes: Add nil and 0 spec checks

- elements/alternativepower.lua
- elements/health.lua
- elements/healthprediction.lua
- elements/portrait.lua
- elements/power.lua
- elements/stagger.lua
> Slightly tweaked Enable funcs

- elements/threatindicator.lua
> threatindicator: Fix UnitThreatSituation error

- .travis.yml
> Revert "Put the changelog in the cloned directory"

- .travis.yml
> Don't restrict builds away from tags

- oUF.toc
How the hell did we miss this...
> Update Interface version

- oUF.toc
> toc: CurseForge wants IDs, not slugs

- elements/classpower.lua
> classpower: Unregister all events

- ouf.lua
> core: Update units of already handled nameplates

- ouf.lua
UNIT_EXITED_VEHICLE does not fire sometimes
Reported on [WoWInterface](http://www.wowinterface.com/forums/showthread.php?p=325455)
> core: update the frame units upon UNIT_EXITING_VEHICLE

- elements/portrait.lua
- events.lua
> Fix portrait updates

- elements/castbar.lua
> castbar: Orientation and reverse fill fix for Spark

- units.lua
Fixes https://github.com/oUF-wow/oUF/issues/410
> core: update arena frames on ARENA_OPPONENT_UPDATE

- utils/changelog
> changelog: Fix link markup

- ouf.lua
Supposedly fixes #423 :grin::gun:
@Blazeflack, @Merathilis, hopefully, this one will work better :D
> core: Update raid vehicle handling hack

- ouf.lua
For some reason we didn't have it o_O
> core: Add frame:IsEnabled() method

- elements/stagger.lua
Typo and copypasta fail removal
> Fix stagger

- ouf.lua
Makes generated names for headers a bit closer to their intended purpose. There are still cases where layouts are better off providing global names themselves.
> Header names

- elements/castbar.lua
> Castbar cleanup

- oUF.xml
- ouf.lua
> core: Proper vehicle fix

- elements/phaseindicator.lua
Respect De Morgan's laws :grin::gun:
And remind me to never push PRs at 4am >_>
> phaseindicator: Fix logic

- elements/additionalpower.lua
> additionalpower: Add option to override the display pairs table

- elements/additionalpower.lua
- elements/alternativepower.lua
- elements/classpower.lua
- elements/combatindicator.lua
- elements/power.lua
- elements/restingindicator.lua
- elements/runes.lua
- ouf.lua
There's many unit checks in the code that were written when there's no nameplate support in oUF which makes using certain elements either very difficult or entirely impossible.
> [WIP] Updates to improve nameplate support

- elements/pvpclassificationindicator.lua
- oUF.xml
> [8.1.5] Add PvPClassificationIndicator element

- oUF.xml
- ouf.lua
``` 
75x Deferred XML Node object named oUF_ClickCastUnitTemplate already exists
```
BEGONE!
> core: Use _initialAttribute-* to set attributes

- elements/powerprediction.lua
>  powerprediction: Fixed a typo

- elements/runes.lua
This typo I made ages ago was brought to my attention today :grin::gun:
> runes: Fixed sorting

- elements/auras.lua
> Fix .tooltipAnchor option and add info about restrictions

- elements/castbar.lua
Fixes https://github.com/oUF-wow/oUF/issues/526
Dry-coded
> castbar: Update safezone position according to the castbar orientation

- elements/tags.lua
> tags: Make the suffix symmetric with the prefix

- elements/phaseindicator.lua
In Shadowlands there's now 4 different types of phases, so simply saying that the unit is phased or nah is no longer enough. I kept `isInSamePhase` for the sake of backwards-compatibility, but in the future only `phaseReason` will be passed to `PostUpdate` since if it's `nil` then units are in the same phase.
> phaseindicator: Pass phaseReason to PostUpdate

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
I find these useful for my own projects.
> Add issue templates

- elements/tags.lua
> tags: Fix suffix extraction

- ouf.lua
> core: signify all AddElement args as mandatory

- combatevents.lua
- oUF.xml
Will probably not see much use, but won't hurt either.
> core: add a combat log event system

- elements/classpower.lua
Can't do the inline check because then only the first element will be seen in `...` 😞🔫
> classpower: Fix chargedPoints unpacking

- elements/auras.lua
Would be nice to do this way, so you can do use Keep Aspect Ratio on Auras 💯
> Keep Aspect Ratio

- .github/workflows/lint.yml
> Disable color output from luacheck

- .luacheckrc
- units.lua
> core: Delay arena prep if in combat

- .luacheckrc
- colors.lua
- elements/additionalpower.lua
- elements/alternativepower.lua
- elements/auras.lua
- elements/classpower.lua
- elements/health.lua
- elements/power.lua
- elements/runes.lua
- elements/stagger.lua
- elements/threatindicator.lua
- units.lua
Closes #590
No BC breaks. I'll switch elements and stuff if you want this. Just left them in for now to demonstrate BC.
> core: use ColorMixin for colors

- elements/castbar.lua
> castbar: Use proper spell names

- .luacheckrc
- blizzard.lua
- colors.lua
- elements/additionalpower.lua
- elements/alternativepower.lua
- elements/auras.lua
- elements/castbar.lua
- elements/classpower.lua
- elements/health.lua
- elements/leaderindicator.lua
- elements/power.lua
- elements/powerprediction.lua
- elements/runes.lua
- elements/stagger.lua
- oUF.toc
- units.lua
This should contain most, if not all of the fixes and features for Dragonflight.
We'll also merge in any other branches from the [11 milestone](https://github.com/oUF-wow/oUF/milestone/12) if time allows it.
> Dragonflight

- elements/classpower.lua
Mere hours after the release of oUF 11, Blizz hit us with another build where they changed stuff... I hope it's the last one.
> classpower: All classes can have charged points

- .luacheckrc
- elements/castbar.lua
Ugh, I was 100% sure I fixed that one... And yes, it's that weirdly named, I double checked...
> castbar: Fix element disabling

- .luacheckrc
- blizzard.lua
> blizzard: Better way of disabling unit frames

- events.lua
> events: Remove unnecessary workaround

- elements/auras.lua
> auras: Process subtables in proper order

- elements/auras.lua
Addresses: https://www.wowinterface.com/forums/showthread.php?p=342127
> auras: Take numTotal into account when adding gap

- .luacheckrc
- blizzard.lua
Ref: https://github.com/Gethe/wow-ui-source/blob/7721fd02dc9425ea89893807f43eaaaa4b7fdd0a/Interface/FrameXML/CompactArenaFrame.lua#L78-L88
> blizzard: Hide the new compact arena frames

- elements/auras.lua
Replace `UnitAuraSlots` with `C_UnitAuras.GetAuraSlots` due to API changes in 10.2.5.
> auras: Update element

- elements/range.lua
> range: Register updater

- elements/totems.lua
Ref: https://github.com/Gethe/wow-ui-source/blob/fa3531505e3e2406f9e3d5a0fbd9644bd5c85227/Interface/AddOns/Blizzard_UnitFrame/TotemFrame.lua#L15-L18
> totems: Follow priorities used by Blizzard

- elements/portrait.lua
> portrait: Cleanup
